### ISSUE TITLE
example4.py does not work for now

### ISSUE THREAD

**Issue by kirienko** [scivision/gpstk-examples-python#1]
example4.py fails at line 48:

``` python
Traceback (most recent call last):
  File "example4.py", line 179, in <module>
    main()
  File "example4.py", line 48, in main
    bcestore.addEphemeris(ephem)
  File "/home/kirienko/.local/lib/python2.7/site-packages/gpstk/gpstk.py", line 15324, in addEphemeris
    return _gpstk.GPSEphemerisStore_addEphemeris(self, *args)
TypeError: in method 'GPSEphemerisStore_addEphemeris', argument 2 of type 'gpstk::GPSEphemeris const &'
```

**Comment by meresmclr** [comment]
Also example 3 is not entirely working correctly. I've updated the install procedure for GPSTk 2.7. At the time I created this repository, I used GPSTk 2.5. The examples were originally written for GPSTk 2.2, and I had to tweak them to make work with GPSTk 2.5, so it's possible that the example files are even more out of date now.

**Comment by meresmclr** [comment]
@kirienko I see that error is inside GPSTk itself, I get it with GPSTk 2.7 released a month ago. 
What I would suggest is consider opening an [Issue at the GPSTk page](https://github.com/SGL-UT/GPSTk/issues) with this info. I'll try to keep an eye on it myself

**Comment by aminhashemi** [comment]
Is there any solution for this matter? I am facing problems even running example3.py

**Comment by meresmclr** [comment]
@aminhashemi I see the latest commit for GPSTk is in May, so I assume it hasn't been addressed yet. I see many people are [opening issues](https://github.com/SGL-UT/GPSTk/issues).
