### ISSUE TITLE
compilation Error in Ubuntu 16

### ISSUE THREAD

**Issue by cartoocm** [scivision/gpstk-examples-python#2]
Hi. After two war days with Conda and gpstk .... :( :( :(

I tried compile gpstk with

`./build.sh -i "%HOME/progs/gpstk" -cdeTp -P "/%HOME/anaconda2/bin/python"`

After that some error

`
Generating Doxygen files from C/C++ source ...
warning: ignoring unknown tag`ext' at line 775, file -
warning: ignoring unknown tag `lib' at line 775, file -
`
...
`In member function ‘const char\* NavFramer::Subframe::checkWords() const’:
cc1plus: warning: function may return address of local variable [-Wreturn-local-addr]
%HOME/dev/GPSTk/ext/apps/swrx/NavFramer.cpp:109:33: note: declared here
       return string("??????????").c_str();
                                 ^
%HOMEdev/GPSTk/ext/lib/Math/Expression.hpp:198: Warning 314: 'print' is a python keyword, renaming to '_print'
%HOME/dev/GPSTk/ext/lib/Math/Expression.hpp:215: Warning 314: 'print' is a python keyword, renaming to '_print'
%HOME/dev/GPSTk/ext/lib/Math/Expression.hpp:233: Warning 314: 'print' is a python keyword, renaming to '_print'
%HOME/dev/GPSTk/ext/lib/Math/Expression.hpp:257: Warning 314: 'print' is a python keyword, renaming to '_print'
%HOME/dev/GPSTk/ext/lib/Math/Expression.hpp:276: Warning 314: 'print' is a python keyword, renaming to '_print'
%HOMEdev/GPSTk/ext/lib/Math/Expression.hpp:311: Warning 314: 'print' is a python keyword, renaming to '_print'

ctest -v -j 12
Errors while running CTest

`
...

`make package_source
./build.sh: línea 278: cd: %HOME/dev/GPSTk/build/vmubuntu-v2.9/swig/install_package: No existe el archivo o el directorio
%HOME/anaconda2/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

8  test failures.
See %HOME/dev/GPSTk/build/vmubuntu-v2.9/Testing/Temporary/LastTest.log for detailed test log
See %HOME/dev/GPSTk/build/vmubuntu-v2.9/build.log for detailed build log
`

I tried compile in two anaconda envs diferents

suggestions?

Thanks

**Comment by meresmclr** [comment]
Hello @cartoocm I see you've opened https://github.com/SGL-UT/GPSTk/issues/20
yes the GPSTk 2.9 install is a bit rough around the edges. I am sorry for this difficulty, I merely tried to patch up their old examples from GPSTk 2.2 so that some of them would work.
But as you noted, this is an issue for https://github.com/SGL-UT/GPSTk/issues/20
